# Generated by Django 4.0 on 2021-12-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('billing_interval', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2500)),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
